language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

install:
  - go get github.com/tools/godep
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

before_script:
  - go vet ./...
  - $GOPATH/bin/godep restore

script: 
  - GORACE="halt_on_error=1" go test -race -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci
